/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GDA.DAO;

import java.util.*;
import java.time.*;


import DAO.DAO.T;
import java.sql.Connection;
// ----------- << imports@AAAAAAGEbMNDTvX2ORU= >>
// ----------- >>

/**
* Classe abstraite des DAO.
*/

// ----------- << class.annotations@AAAAAAGEbMNDTvX2ORU= >>
// ----------- >>
public abstract class DAO<T> {
    // ----------- << attribute.annotations@AAAAAAGEbNHL2fe9SDc= >>
    // ----------- >>
    private Connection conn;

    protected Connection getConn() {
        return conn;
    }

    /**
    * Constructeur de DAO.
    * @param conn une Connection représentant la connexion à la base de données.
    */

    // ----------- << method.annotations@AAAAAAGEesWO0wDAWG8= >>
    // ----------- >>
    public DAO(Connection conn) {
    // ----------- << method.body@AAAAAAGEesWO0wDAWG8= >>
    // ----------- >>
    }
    /**
    * Récupère dans la base de données l'instance de T demandée.
    * @param id id de type int, représente l'id de l'objet T demandé.
    * @returns Une instance de T.
    */

    // ----------- << method.annotations@AAAAAAGEbNLXdvfIIVM= >>
    // ----------- >>
    public abstract T get(int id);
    /**
    * Récupère dans la base de données toutes les instances de T.
    * @returns Une liste d'instances de T.
    */

    // ----------- << method.annotations@AAAAAAGEesCaleu+4ys= >>
    // ----------- >>
    public abstract List<T> getAll();
    /**
    * Ajoute dans la base de données une instance de T.
    * @param t l'instance T de l'objet à ajouter.
    */

    // ----------- << method.annotations@AAAAAAGEbNLv1vfU89g= >>
    // ----------- >>
    public abstract void add(T t);
    /**
    * Met à jour dans la base de données une instance de T.
    * @param t l'instance T de l'objet à mettre à jour.
    */

    // ----------- << method.annotations@AAAAAAGEbNL5svfab9s= >>
    // ----------- >>
    public abstract void update(T t);
    /**
    * Supprime de la base de données  l'instance de T associée à l'id.
    * @param id int représentant l'id de T à supprimer.
    */

    // ----------- << method.annotations@AAAAAAGEbNWAKffjF44= >>
    // ----------- >>
    public abstract void delete(int id);
// ----------- << class.extras@AAAAAAGEbMNDTvX2ORU= >>
// ----------- >>
}