/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhRbicig0blU= >>
// ----------- >>

/**
* Contrôleur permettant l'ajout d'un Administrateur.
*/

// ----------- << class.annotations@AAAAAAGEhRbicig0blU= >>
// ----------- >>
public class AddAdminCtrl {
// ----------- << class.extras@AAAAAAGEhRbicig0blU= >>
// ----------- >>
}