/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhQDpLdt3wsY= >>
// ----------- >>

/**
* Contrôleur permettant l'ajout d'une Commande.
*/

// ----------- << class.annotations@AAAAAAGEhQDpLdt3wsY= >>
// ----------- >>
public class AddCommCtrl {
// ----------- << class.extras@AAAAAAGEhQDpLdt3wsY= >>
// ----------- >>
}