/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhRl1zGMFi0E= >>
// ----------- >>

/**
* Contrôleur permettant l'ajout d'un Client.
*/

// ----------- << class.annotations@AAAAAAGEhRl1zGMFi0E= >>
// ----------- >>
public class AddClientCtrl {
// ----------- << class.extras@AAAAAAGEhRl1zGMFi0E= >>
// ----------- >>
}