/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package controllers;


// ----------- << imports@AAAAAAGEhRgcFy/Ioj4= >>
// ----------- >>

/**
* Contrôleur permettant l'ajout d'un Producteur.
*/

// ----------- << class.annotations@AAAAAAGEhRgcFy/Ioj4= >>
// ----------- >>
public class AddProdCtrl {
// ----------- << class.extras@AAAAAAGEhRgcFy/Ioj4= >>
// ----------- >>
}