/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhQ713PxUkoM= >>
// ----------- >>

/**
* Contrôleur permettant l'ajout d'une Tournee.
*/

// ----------- << class.annotations@AAAAAAGEhQ713PxUkoM= >>
// ----------- >>
public class AddTourneeCtrl {
// ----------- << class.extras@AAAAAAGEhQ713PxUkoM= >>
// ----------- >>
}