/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhRCGxR8mvqc= >>
// ----------- >>

/**
* Contrôleur permettant l'ajout d'un Vehicule.
*/

// ----------- << class.annotations@AAAAAAGEhRCGxR8mvqc= >>
// ----------- >>
public class AddVehiculeCtrl {
// ----------- << class.extras@AAAAAAGEhRCGxR8mvqc= >>
// ----------- >>
}