/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhQcoc3R2dTc= >>
// ----------- >>

/**
* Contrôleur de la page profil de l'Administrateur.
*/

// ----------- << class.annotations@AAAAAAGEhQcoc3R2dTc= >>
// ----------- >>
public class AdminProfileCtrl {
// ----------- << class.extras@AAAAAAGEhQcoc3R2dTc= >>
// ----------- >>
}