/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhP2wGndC7XU= >>
// ----------- >>

/**
* Contrôleur permettant la consultation Administrateur.
*/

// ----------- << class.annotations@AAAAAAGEhP2wGndC7XU= >>
// ----------- >>
public class AdminConsultCtrl {
// ----------- << class.extras@AAAAAAGEhP2wGndC7XU= >>
// ----------- >>
}