/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhRF4BEAU5g0= >>
// ----------- >>

/**
* Contrôleur permettant l'aperçu d'un Vehicule.
*/

// ----------- << class.annotations@AAAAAAGEhRF4BEAU5g0= >>
// ----------- >>
public class ApercuVehiculeCtrl {
// ----------- << class.extras@AAAAAAGEhRF4BEAU5g0= >>
// ----------- >>
}