/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package controllers;


// ----------- << imports@AAAAAAGEhQp8frstQ70= >>
// ----------- >>

/**
* Contrôleur permettant l'aperçu Commande.
*/

// ----------- << class.annotations@AAAAAAGEhQp8frstQ70= >>
// ----------- >>
public class ApercuCommCtrl {
// ----------- << class.extras@AAAAAAGEhQp8frstQ70= >>
// ----------- >>
}