/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhRfHjyyXD3M= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEhRfHjyyXD3M= >>
// ----------- >>
public class ApercuAdminCtrl {
// ----------- << class.extras@AAAAAAGEhRfHjyyXD3M= >>
// ----------- >>
}