/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhRj1W04stJk= >>
// ----------- >>

/**
* Contrôleur permettant l'aperçu Producteur.
*/

// ----------- << class.annotations@AAAAAAGEhRj1W04stJk= >>
// ----------- >>
public class ApercuProdCtrl {
// ----------- << class.extras@AAAAAAGEhRj1W04stJk= >>
// ----------- >>
}