/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhR1syrb8V1E= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEhR1syrb8V1E= >>
// ----------- >>
public class ApercuTourneeCtrl {
// ----------- << class.extras@AAAAAAGEhR1syrb8V1E= >>
// ----------- >>
}s.extras@AAAAAAGEhR8O+OxAveQ= >>
// ----------- >>
}