/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhR8O+OxAveQ= >>
// ----------- >>

/**
* Contrôleur permettant l'aperçu Tournee.
*/

// ----------- << class.annotations@AAAAAAGEhR8O+OxAveQ= >>
// ----------- >>
public class ApercuTourneeCtrl {
// ----------- << class.extras@AAAAAAGEhR8O+OxAveQ= >>
// ----------- >>
}