/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package controllers;


import modele.ModeleConcret;
// ----------- << imports@AAAAAAGEhnqZ32YLAiU= >>
// ----------- >>

/**
* Contrôleur commun.
*/

// ----------- << class.annotations@AAAAAAGEhnqZ32YLAiU= >>
// ----------- >>
public class ConcreteController {
    /**
    * @param e
    */

    // ----------- << method.annotations@AAAAAAGEhnsx4nk6+w0= >>
    // ----------- >>
    public void ActionPerformed(ActionEvent e) {
    // ----------- << method.body@AAAAAAGEhnsx4nk6+w0= >>
    // ----------- >>
    }
    /**
    * @param m
    */

    // ----------- << method.annotations@AAAAAAGEhnusdn9z5Sk= >>
    // ----------- >>
    public void SetModele(ModeleConcret m) {
    // ----------- << method.body@AAAAAAGEhnusdn9z5Sk= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEhnqZ32YLAiU= >>
// ----------- >>
}