/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package controllers;


// ----------- << imports@AAAAAAGEhPnwjMYabXE= >>
// ----------- >>

/**
* Contrôleur de la page d'accueil.
*/

// ----------- << class.annotations@AAAAAAGEhPnwjMYabXE= >>
// ----------- >>
public class HomePageCtrl {
// ----------- << class.extras@AAAAAAGEhPnwjMYabXE= >>
// ----------- >>
}