/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhRnnyG6Dq2c= >>
// ----------- >>

/**
* Contrôleur permettant la modification d'un Client.
*/

// ----------- << class.annotations@AAAAAAGEhRnnyG6Dq2c= >>
// ----------- >>
public class ModifClientCtrl {
// ----------- << class.extras@AAAAAAGEhRnnyG6Dq2c= >>
// ----------- >>
}