/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhQEjG984vcE= >>
// ----------- >>

/**
* Contrôleur permettant la modification d'une Commande.
*/

// ----------- << class.annotations@AAAAAAGEhQEjG984vcE= >>
// ----------- >>
public class ModifCommCtrl {
// ----------- << class.extras@AAAAAAGEhQEjG984vcE= >>
// ----------- >>
}