/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package controllers;


// ----------- << imports@AAAAAAGEhQ+uGQo8sYQ= >>
// ----------- >>

/**
* Contrôleur permettant la modification d'une Tournee.
*/

// ----------- << class.annotations@AAAAAAGEhQ+uGQo8sYQ= >>
// ----------- >>
public class ModifTourneeCtrl {
// ----------- << class.extras@AAAAAAGEhQ+uGQo8sYQ= >>
// ----------- >>
}