/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhRhXNjOJax0= >>
// ----------- >>

/**
* Contrôleur permettant la modification d'un Producteur.
*/

// ----------- << class.annotations@AAAAAAGEhRhXNjOJax0= >>
// ----------- >>
public class ModifProdCtrl {
// ----------- << class.extras@AAAAAAGEhRhXNjOJax0= >>
// ----------- >>
}