/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhPpCMNM2pIY= >>
// ----------- >>

/**
* Contrôleur permettant la connexion d'un Producteur.
*/

// ----------- << class.annotations@AAAAAAGEhPpCMNM2pIY= >>
// ----------- >>
public class ProdConnCtrl {
// ----------- << class.extras@AAAAAAGEhPpCMNM2pIY= >>
// ----------- >>
}