/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhQeGdXzwzog= >>
// ----------- >>

/**
* Contrôleur de la page profil du Producteur.
*/

// ----------- << class.annotations@AAAAAAGEhQeGdXzwzog= >>
// ----------- >>
public class ProdProfileCtrl extends ProfileCtrl {
// ----------- << class.extras@AAAAAAGEhQeGdXzwzog= >>
// ----------- >>
}