/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package controllers;


// ----------- << imports@AAAAAAGEhP6p+ZGGFd4= >>
// ----------- >>

/**
* Contrôleur de la page profil.
*/

// ----------- << class.annotations@AAAAAAGEhP6p+ZGGFd4= >>
// ----------- >>
public class ProfileCtrl {
// ----------- << class.extras@AAAAAAGEhP6p+ZGGFd4= >>
// ----------- >>
}