/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhQLSzkEd/Ao= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEhQLSzkEd/Ao= >>
// ----------- >>
public class Profil {
// ----------- << class.extras@AAAAAAGEhQLSzkEd/Ao= >>
// ----------- >>
}--- >>
}