/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package controllers;


// ----------- << imports@AAAAAAGEhRBKsB1dXKQ= >>
// ----------- >>

/**
* Contrôleur permettant la suppression d'un Vehicule.
*/

// ----------- << class.annotations@AAAAAAGEhRBKsB1dXKQ= >>
// ----------- >>
public class SupprVehiculeCtrl {
// ----------- << class.extras@AAAAAAGEhRBKsB1dXKQ= >>
// ----------- >>
}