/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package controllers;


// ----------- << imports@AAAAAAGEhQFjc+Un2Fk= >>
// ----------- >>

/**
* Contrôleur permettant la suppression d'une Commande.
*/

// ----------- << class.annotations@AAAAAAGEhQFjc+Un2Fk= >>
// ----------- >>
public class SupprCommtrl {
// ----------- << class.extras@AAAAAAGEhQFjc+Un2Fk= >>
// ----------- >>
}