/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Controllers;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhRoQu3ESKnQ= >>
// ----------- >>

/**
* Contrôleur permettant la suppression d'un Client.
*/

// ----------- << class.annotations@AAAAAAGEhRoQu3ESKnQ= >>
// ----------- >>
public class SupprClientCtrl {
// ----------- << class.extras@AAAAAAGEhRoQu3ESKnQ= >>
// ----------- >>
}