/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package controllers;


// ----------- << imports@AAAAAAGEhQ/1kBHwvK4= >>
// ----------- >>

/**
* Contrôleur permettant la suppression d'une Tournee.
*/

// ----------- << class.annotations@AAAAAAGEhQ/1kBHwvK4= >>
// ----------- >>
public class SupprTourneeCtrl {
// ----------- << class.extras@AAAAAAGEhQ/1kBHwvK4= >>
// ----------- >>
}