/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package controllers;


// ----------- << imports@AAAAAAGEhRiOVDbwxWk= >>
// ----------- >>

/**
* Contrôleur permettant la suppression d'un Producteur.
*/

// ----------- << class.annotations@AAAAAAGEhRiOVDbwxWk= >>
// ----------- >>
public class SupprProdCtrl {
// ----------- << class.extras@AAAAAAGEhRiOVDbwxWk= >>
// ----------- >>
}