/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GDA.Utility;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhpj48DpuqBk= >>
// ----------- >>

/**
* Génère une carte de la zone demandée.
*/

// ----------- << class.annotations@AAAAAAGEhpj48DpuqBk= >>
// ----------- >>
public class GenerateurMap {
// ----------- << class.extras@AAAAAAGEhpj48DpuqBk= >>
// ----------- >>
}