/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GDA.Utility;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhplc40rVhBo= >>
// ----------- >>

/**
* Valide ou pas les entrées fournies.
*/

// ----------- << class.annotations@AAAAAAGEhplc40rVhBo= >>
// ----------- >>
public class ValidateurDonnee {
    // ----------- << method.annotations@AAAAAAGEhpm+kmWn6Nc= >>
    // ----------- >>
    public void valideCiret() {
    // ----------- << method.body@AAAAAAGEhpm+kmWn6Nc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEhpndiWfuoX4= >>
    // ----------- >>
    public void valideAdresse() {
    // ----------- << method.body@AAAAAAGEhpndiWfuoX4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGEhpoIjGslyN4= >>
    // ----------- >>
    public void valideNom() {
    // ----------- << method.body@AAAAAAGEhpoIjGslyN4= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEhplc40rVhBo= >>
// ----------- >>
}