/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package utility;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhqAxFy+ZazU= >>
// ----------- >>

/**
* Valide ou pas la tournée paramétrée.
*/

// ----------- << class.annotations@AAAAAAGEhqAxFy+ZazU= >>
// ----------- >>
public class ValidateurTournee {
// ----------- << class.extras@AAAAAAGEhqAxFy+ZazU= >>
// ----------- >>
}