/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Modele;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEZ1O5lBbdGrk= >>
// ----------- >>

/**
* Métier représentant un Administrateur.
*/

// ----------- << class.annotations@AAAAAAGEZ1O5lBbdGrk= >>
// ----------- >>
public class Administrateur extends ModeleConcret {
    // ----------- << attribute.annotations@AAAAAAGEbG98vexw6nU= >>
    // ----------- >>
    private int idAdministrateur;

    // ----------- << attribute.annotations@AAAAAAGEbG+LZOx2bs4= >>
    // ----------- >>
    private String pseudo;

    // ----------- << attribute.annotations@AAAAAAGEbG+bM+x8dIo= >>
    // ----------- >>
    private String mdpAdmin;

    private int getIdAdministrateur() {
        return idAdministrateur;
    }

    private String getPseudo() {
        return pseudo;
    }

    private String getMdpAdmin() {
        return mdpAdmin;
    }

    private void setIdAdministrateur(int idAdministrateur) {
        this.idAdministrateur = idAdministrateur;
    }

    private void setPseudo(String pseudo) {
        this.pseudo = pseudo;
    }

    private void setMdpAdmin(String mdpAdmin) {
        this.mdpAdmin = mdpAdmin;
    }

    /**
    * Constructeur d'Administrateur.
    * @param idAdministrateur int représentant l'Administrateur.
    * @param pseudo String représentant l'Administrateur.
    * @param mdpAdmin String représentant l'Administrateur.
    */

    // ----------- << method.annotations@AAAAAAGEbG+1n+yC4T8= >>
    // ----------- >>
    public Administrateur(int idAdministrateur, String pseudo, String mdpAdmin) {
    // ----------- << method.body@AAAAAAGEbG+1n+yC4T8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEZ1O5lBbdGrk= >>
// ----------- >>
}