/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GDA.Modele;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEbHKJxuymjCY= >>
// ----------- >>

/**
* Métier représentant un client.
*/

// ----------- << class.annotations@AAAAAAGEbHKJxuymjCY= >>
// ----------- >>
public class Client extends ModeleConcret {
    // ----------- << attribute.annotations@AAAAAAGEbHKpLuzQ+2k= >>
    // ----------- >>
    private int idClient;

    // ----------- << attribute.annotations@AAAAAAGEbHK6t+zWDq4= >>
    // ----------- >>
    private String nomClient;

    // ----------- << attribute.annotations@AAAAAAGEbHLbMezcG5M= >>
    // ----------- >>
    private String adresseClient;

    // ----------- << attribute.annotations@AAAAAAGEbHLm7uziF4k= >>
    // ----------- >>
    private String gpsClient;

    // ----------- << attribute.annotations@AAAAAAGEbHL1ROzoSQk= >>
    // ----------- >>
    private String numTelClient;

    // ----------- << attribute.annotations@AAAAAAGEeqR6ThqNbs0= >>
    // ----------- >>
    private List<Commande> commandes = new ArrayList<>();

    private int getIdClient() {
        return idClient;
    }

    private String getNomClient() {
        return nomClient;
    }

    private String getAdresseClient() {
        return adresseClient;
    }

    private String getGpsClient() {
        return gpsClient;
    }

    private String getNumTelClient() {
        return numTelClient;
    }

    private List<Commande> getCommandes() {
        return commandes;
    }

    private void setIdClient(int idClient) {
        this.idClient = idClient;
    }

    private void setNomClient(String nomClient) {
        this.nomClient = nomClient;
    }

    private void setAdresseClient(String adresseClient) {
        this.adresseClient = adresseClient;
    }

    private void setGpsClient(String gpsClient) {
        this.gpsClient = gpsClient;
    }

    private void setNumTelClient(String numTelClient) {
        this.numTelClient = numTelClient;
    }

    /**
    * Constructeur de Client.
    * @param idClient int représentant l'id du Client.
    * @param nomClient String représentant le nom du Client.
    * @param adresseClient String représentant l'adresse du Client.
    * @param gpsClient String représentant les coordonnées GPS du Client.
    * @param numTelClient String représentant le numéro de téléphone du Client.
    * @param commandes ArrayList<Commande> représentant les commandes du Client.
    */

    // ----------- << method.annotations@AAAAAAGEbHMD+uzuRZI= >>
    // ----------- >>
    public Client(int idClient, String nomClient, String adresseClient, String gpsClient, String numTelClient, List<Commande> commandes) {
    // ----------- << method.body@AAAAAAGEbHMD+uzuRZI= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEbHKJxuymjCY= >>
// ----------- >>
}