/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package modele;


import java.util.Observable;
// ----------- << imports@AAAAAAGEhmw+ZSvzfcw= >>
// ----------- >>

/**
* Métier commun.
*/

// ----------- << class.annotations@AAAAAAGEhmw+ZSvzfcw= >>
// ----------- >>
public class ModeleConcret extends Observable {
// ----------- << class.extras@AAAAAAGEhmw+ZSvzfcw= >>
// ----------- >>
}