/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package modele;

import java.util.*;


// ----------- << imports@AAAAAAGEZ1SqzBcyy88= >>
// ----------- >>

/**
* Métier représentant une Tournée.
*/

// ----------- << class.annotations@AAAAAAGEZ1SqzBcyy88= >>
// ----------- >>
public class Tournee extends ModeleConcret {
    // ----------- << attribute.annotations@AAAAAAGEZ9f7R/ABTqQ= >>
    // ----------- >>
    private int idTournee;

    // ----------- << attribute.annotations@AAAAAAGEZ9gGFvBD5sU= >>
    // ----------- >>
    private String horaireDebut;

    // ----------- << attribute.annotations@AAAAAAGEZ9gXLPCFrfM= >>
    // ----------- >>
    private String horaireFin;

    // ----------- << attribute.annotations@AAAAAAGEZ9goaPDHpxU= >>
    // ----------- >>
    private float poids;

    // ----------- << attribute.annotations@AAAAAAGEZ+CQwhhUzZs= >>
    // ----------- >>
    private Vehicule vehicule;

    // ----------- << attribute.annotations@AAAAAAGEddgjn+ucgcE= >>
    // ----------- >>
    private List<Commande> commandes = new ArrayList<>();

    private int getIdTournee() {
        return idTournee;
    }

    private String getHoraireDebut() {
        return horaireDebut;
    }

    private String getHoraireFin() {
        return horaireFin;
    }

    private float getPoids() {
        return poids;
    }

    private Vehicule getVehicule() {
        return vehicule;
    }

    private List<Commande> getCommandes() {
        return commandes;
    }

    private void setIdTournee(int idTournee) {
        this.idTournee = idTournee;
    }

    private void setHoraireDebut(String horaireDebut) {
        this.horaireDebut = horaireDebut;
    }

    private void setHoraireFin(String horaireFin) {
        this.horaireFin = horaireFin;
    }

    private void setPoids(float poids) {
        this.poids = poids;
    }

    private void setVehicule(Vehicule vehicule) {
        this.vehicule = vehicule;
    }

    /**
    * Constructeur de Tournee.
    * @param idTournee int représentant l'id de la Tournee.
    * @param horaireDebut String représentant l'horaire de début de la Tournee.
    * @param horaireFin String représentant l'horaire de fin de la Tournee.
    * @param poids float représentant le poids total de la Tournee.
    * @param vehicule Vehicule représentant le véhicule utilisé pour effectuer la Tournee.
    * @param commandes ArrayList<Commande> représentant les commandes composant la Tournee.
    */

    // ----------- << method.annotations@AAAAAAGEZ9hvY/Jgtfc= >>
    // ----------- >>
    public Tournee(int idTournee, String horaireDebut, String horaireFin, float poids, Vehicule vehicule, List<Commande> commandes) {
    // ----------- << method.body@AAAAAAGEZ9hvY/Jgtfc= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEZ1SqzBcyy88= >>
// ----------- >>
}