/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package modele;

import java.util.*;


// ----------- << imports@AAAAAAGEZ1Oy0Ra0R8I= >>
// ----------- >>

/**
* Métier représentant un Véhicule.
*/

// ----------- << class.annotations@AAAAAAGEZ1Oy0Ra0R8I= >>
// ----------- >>
public class Vehicule extends ModeleConcret {
    // ----------- << attribute.annotations@AAAAAAGEaBCEjfJZ7Vg= >>
    // ----------- >>
    private int idVehicule;

    // ----------- << attribute.annotations@AAAAAAGEaA4lzuylNe4= >>
    // ----------- >>
    private String numImmat;

    // ----------- << attribute.annotations@AAAAAAGEaA46A+0LF2k= >>
    // ----------- >>
    private float poidsMax;

    // ----------- << attribute.annotations@AAAAAAGEdakZe233zYo= >>
    // ----------- >>
    private List<Tournee> tournees = new ArrayList<>();

    // ----------- << attribute.annotations@AAAAAAGEddGkMqsRlk4= >>
    // ----------- >>
    private Producteur producteur;

    private int getIdVehicule() {
        return idVehicule;
    }

    private String getNumImmat() {
        return numImmat;
    }

    private float getPoidsMax() {
        return poidsMax;
    }

    private List<Tournee> getTournees() {
        return tournees;
    }

    private Producteur getProducteur() {
        return producteur;
    }

    private void setIdVehicule(int idVehicule) {
        this.idVehicule = idVehicule;
    }

    private void setNumImmat(String numImmat) {
        this.numImmat = numImmat;
    }

    private void setPoidsMax(float poidsMax) {
        this.poidsMax = poidsMax;
    }

    private void setProducteur(Producteur producteur) {
        this.producteur = producteur;
    }

    /**
    * Constructeur de Vehicule.
    * @param idVehicule int représentant l'id du Vehicule.
    * @param numImmat String représentant le numéro d'immatriculation du Vehicule.
    * @param poidsMax float représentant le poids maximum que le Vehicule peut accepter.
    * @param producteur Producteur représentant le producteur utilisant le Vehicule.
    * @param tournees ArrayList<Tournee> représentant les tournées du Vehicule.
    */

    // ----------- << method.annotations@AAAAAAGEaA4XfuwnJ88= >>
    // ----------- >>
    public Vehicule(int idVehicule, String numImmat, float poidsMax, Producteur producteur, List<Tournee> tournees) {
    // ----------- << method.body@AAAAAAGEaA4XfuwnJ88= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEZ1Oy0Ra0R8I= >>
// ----------- >>
}