/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhnXbBhQCo5c= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEhnXbBhQCo5c= >>
// ----------- >>
public class ConcreteView {
    /**
    * @param c
    */

    // ----------- << method.annotations@AAAAAAGEhneXyy9V824= >>
    // ----------- >>
    public void setController(ActionListener c) {
    // ----------- << method.body@AAAAAAGEhneXyy9V824= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEhnXbBhQCo5c= >>
// ----------- >>
}