/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GDA;

import java.util.*;
import java.time.*;


import java.sql.Connection;
// ----------- << imports@AAAAAAGEbJAWDu7oWNM= >>
// ----------- >>

/**
* Représente la connexion à la base de données.
*/

// ----------- << class.annotations@AAAAAAGEbJAWDu7oWNM= >>
// ----------- >>
public class DatabaseConnection {
    // ----------- << attribute.annotations@AAAAAAGEbJQd3u80YGI= >>
    // ----------- >>
    private static String url;

    // ----------- << attribute.annotations@AAAAAAGEbJQpWu86j3c= >>
    // ----------- >>
    private static String username;

    // ----------- << attribute.annotations@AAAAAAGEbJQ1fe9ALvo= >>
    // ----------- >>
    private static String password;

    // ----------- << attribute.annotations@AAAAAAGEbMlNMPZcwqc= >>
    // ----------- >>
    private static Connection conn;

    /**
    * Permet d'obtenir l'instance Connection partagée.
    * @returns une Connection, l'instance commune à tous les DAO.
    */

    // ----------- << method.annotations@AAAAAAGEbJI1t+8bHXY= >>
    // ----------- >>
    public static Connection getInstance() {
    // ----------- << method.body@AAAAAAGEbJI1t+8bHXY= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEbJAWDu7oWNM= >>
// ----------- >>
}