/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEZ1UffBdd/to= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEZ1UffBdd/to= >>
// ----------- >>
public class GDA {
    /**
    * @param args
    */

    // ----------- << method.annotations@AAAAAAGEZ1n7GRe/E7Q= >>
    // ----------- >>
    public static void main(String args) {
    // ----------- << method.body@AAAAAAGEZ1n7GRe/E7Q= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGEZ1UffBdd/to= >>
// ----------- >>
}