/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package GDA;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGEhpj48DpuqBk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGEhpj48DpuqBk= >>
// ----------- >>
public class GenerateurMap {
// ----------- << class.extras@AAAAAAGEhpj48DpuqBk= >>
// ----------- >>
}